/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 14e125d6d4ae127bad282f8a24a77d24)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "EmailServiceAgent";
  }
  interface Env {
    EMAIL: SendEmail;
    EMAIL_FROM: "meetme@inboxbuddy.dev";
    EmailServiceAgent: DurableObjectNamespace<
      import("./src/server").EmailServiceAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "EMAIL_FROM">
  > {}
}
